apiVersion: v1
kind: ConfigMap
metadata:
  name: __K8S_APP_NAME__-configmap
  namespace: __K8S_NAMESPACE__
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: "__APPINSIGHTS_INSTRUMENTATIONKEY__"
  AspNetCorePathBase: "__K8S_APP_ROUTE__" 
  TenantId: "__TENANT_ID__" 
  KeyVaultName: "__K8S_APP_KV_NAME__" 
  DbServerName: "__DB_SERVER_NAME__" 
  DbName: "__DB_NAME__" 
