version: '3.4'
services:
  home-assistant:
    image: homeassistant/home-assistant:0.108.8
    container_name: home-assistant
    ports:
        - 8123:8123
    volumes:
      - ./homeassistant:/config

  mqtt:
    container_name: mosquitto
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    ports:
        - 1883:1883
        - 9001:9001
    volumes:
    - ./log/mqtt:/mqtt/log
    - ./data/mqtt:/mqtt/data/
